PREFIX lemonEty: <http://lari-datasets.ilc.cnr.it/lemonEty#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX lime: <http://www.w3.org/ns/lemon/lime#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX lila: <http://lila-erc.eu/ontologies/lila/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX powla: <http://purl.org/powla/powla.owl#>
PREFIX vartrans: <http://www.w3.org/ns/lemon/vartrans#>
PREFIX prinparlat: <http://lila-erc.eu/ontologies/prinparlat/>

#count the number of lemmas descending from a causative-iterative stem per inflection type

SELECT   ?inflectiontypelabel (COUNT (DISTINCT ?lemma) as ?lemmacount) WHERE {
  ?lemma rdf:type lila:Lemma;
         lila:hasInflectionType ?inflectiontype;
         rdfs:label ?lemmalabel.
  ?inflectiontype rdfs:label ?inflectiontypelabel.
<http://lila-erc.eu/data/lexicalResources/LIV/Lexicon> lime:entry ?livlexentry.
  ?livlexentry ontolex:canonicalForm ?lemma;
               vartrans:lexicalRel ?latstem.
  ?etylink lemonEty:etyTarget ?latstem;
           lemonEty:etySource ?piestem.
  ?piestem prinparlat:stemType ?piestemtype.
  VALUES ?piestemtype {<http://lila-erc.eu/data/lexicalResources/LIV/id/LexicalEntry/id/Stems/causative–iterative_stem>}
  
}
ORDER BY DESC (?lemmacount)